### ISSUE TITLE
2to3 works, but breaks actual functionality

### ISSUE THREAD

**Issue by txoof** [elParaguayo/LMSTools#17]
I was super excited to find this code. It's exactly what I need for an ePaper/Rasperry Pi SqueezeBox that I'm building. 

Is there any chance you are going to continue to maintain this and move it to Python 3?

I tried to migrate it to python 3, but failed miserably. The python 3 urllib2->urllib mess breaks something deep within the guts. 

I haven't had the pythonFu to figure out what goes wrong, but the symptoms are pretty interesting:

```
server = LMSServer('media-server.local')
print(server.get_player_count())
>>> 0

```

The same code run under python2 works just fine. Clearly something's busted.

**Comment by elParaguayo** [comment]
Hi txoof.

I can take a look but I can't guarantee any timeframe for you. Life's busy so I don't have a huge amount of any of these projects any more.

**Comment by elParaguayo** [comment]
As I recall, I had issues with the callbackserver on python 3 but I don't remember the LMSServer not working.

**Comment by aschamberger** [comment]
Did you use my fork from my pull request: #16?

**Comment by elParaguayo** [comment]
No, but that might be enough for txoof.

Thanks!

**Comment by txoof** [comment]
@aschamberger 
What's the best way for me to use your pull request? I'm pretty novice to VCS and github in general. Do I just do a clone of your repo and start working from there?

**Comment by txoof** [comment]
I ended up rewriting this and creating my own library: [QueryLMS](https://github.com/txoof/querylms). I borrowed a lot of your code, and manages to create a simplified version.

**Comment by elParaguayo** [comment]
Nice. Thanks for letting me know.
