### ISSUE TITLE
Add method for player to check event notifications

### ISSUE THREAD

**Issue by elParaguayo** [elParaguayo/LMSTools#7]
Player should be able to confirm if event refers to the specified player or a player in the same sync group.

**Comment by bitShakeMX** [comment]
Hi, How i can navigate on my local library with to get the url of the songs?

**Comment by elParaguayo** [comment]
Have you read the documentation? You could do this via the [menu handler](http://lmstools.readthedocs.io/en/latest/examples/menus.html) and work your way through the menus as you would on a swueezeplayer.

How are you planning on selecting which music to play?

Lastly, this should really be in a new issue as it's got nothing to do with the original question posted.
